apiVersion: apps/v1
kind: Deployment
metadata:
  name: freeln-order
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freeln-order
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: freeln-order
    spec:
      containers:
        - name: freeln-order
          image: datz0512/freelancer-order:stable
          imagePullPolicy: Always
          resources:
            limits:
              memory: '1Gi'
              cpu: '0.5'
            requests:
              cpu: 100m
              memory: 150Mi
          ports:
            - name: order
              containerPort: 4006
          env:
            - name: ENABLE_APM
              value: '1'
            - name: NODE_ENV
              value: 'production'
            - name: GATEWAY_JWT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: freelance-backend-secret
                  key: gateway-jwt-token
            - name: JWT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: freelance-backend-secret
                  key: jwt-token
            - name: RABBITMQ_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: freelance-backend-secret
                  key: freelance-rabbitmq-endpoint
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: freelance-backend-secret
                  key: mongo-database-url
            - name: CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: freelance-backend-secret
                  key: cloud-name
            - name: CLOUD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: freelance-backend-secret
                  key: cloud-api-key
            - name: CLOUD_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: freelance-backend-secret
                  key: cloud-api-secret
            - name: API_GATEWAY_URL
              value: 'http://freelance-gateway:4000'
            - name: CLIENT_URL
              value: 'http://localhost:3000'
            - name: STRIPE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: freelance-backend-secret
                  key: stripe-api-key
            - name: ELASTIC_SEARCH_URL
              valueFrom:
                secretKeyRef:
                  name: freelance-backend-secret
                  key: freelance-elasticsearch-url
            - name: ELASTIC_APM_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: freelance-backend-secret
                  key: freelance-elastic-apm-server-url
            - name: ELASTIC_APM_SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: freelance-backend-secret
                  key: freelance-elastic-apm-secret-token
