apiVersion: v1
kind: Service
metadata:
  name: freeln-order
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: freeln-order
  ports:
    - name: order
      port: 4006
      targetPort: 4006
      protocol: TCP
