apiVersion: v1
kind: Service
metadata:
  name: freelance-mongo
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: freelance-mongo
  ports:
    - name: freelance-mongo
      port: 27017
      targetPort: 27017
