# You can check this https://sourcegraph.com/github.com/elastic/beats/-/blob/metricbeat/metricbeat.reference.yml
metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    # Reload module configs as they change:
    reload.enabled: false

metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

metricbeat.modules:
  - module: docker
    metricsets:
      - 'container'
      - 'cpu'
      - 'diskio'
      - 'healthcheck'
      - 'info'
      - 'memory'
      - 'network'
    hosts: ['unix:///var/run/docker.sock']
    period: 10s
    enabled: true

  - module: system
    metricsets:
      - cpu # CPU usage
      - load # CPU load averages
      - memory # Memory usage
      - network # Network IO
      - process # Per process metrics
      - process_summary # Process summary
      - uptime # System Uptime
      - socket_summary # Socket summary
      - core # Per CPU core usage
      - diskio # Disk IO
      - filesystem # File system usage for each mountpoint
      - fsstat # File system summary metrics
      - socket # Sockets and connection info (linux only)
    enabled: true
    period: 10s
    processes: ['.*']
    hostfs: '/hostfs'
    cpu.metrics: ['percentages', 'normalized_percentages']
    core.metrics: ['percentages']

  - module: rabbitmq
    metricsets: ['node', 'queue', 'connection', 'exchange', 'shovel']
    enabled: true
    period: 10s
    hosts: ['127.0.0.1:15672']

  - module: mongodb
    metricsets: ['dbstats', 'status', 'collstats', 'metrics', 'replstatus']
    period: 10s
    enabled: true
    # The hosts must be passed as MongoDB URLs in the format:
    # [mongodb://][user:pass@]host[:port].
    # The username and password can also be set using the respective configuration
    # options. The credentials in the URL take precedence over the username and
    # password configuration options.
    hosts: ['mongodb://127.0.0.1:27017']

  - module: mysql
    metricsets:
      - status
      - performance
    period: 10s
    hosts: ['tcp(127.0.0.1:3306)/']
    username: freelancer
    password: api

  - module: postgresql
    enabled: true
    metricsets:
      - database
      - bgwriter
      - activity

    period: 10s
    hosts: ['postgres://127.0.0.1:5432']
    username: freelancer
    password: api

processors:
  - add_cloud_metadata: ~

output.elasticsearch:
  hosts: ['http://elasticsearch_container:9200']
  username: 'elastic'
  password: 'admin1234'
