apiVersion: v1
kind: Service
metadata:
  name: freelance-postg
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: freelance-postg
  ports:
    - name: freelance-postg
      port: 5432
      targetPort: 5432
