apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  namespace: production
spec:
  storageClassName: redis-local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/storage/data1'
