apiVersion: v1
kind: Service
metadata:
  name: freelance-redis
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: freelance-redis
  ports:
    - name: freelance-redis
      port: 6379
      targetPort: 6379
