apiVersion: v1
kind: Service
metadata:
  name: freeln-users
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: freeln-users
  ports:
    - name: users
      port: 4003
      targetPort: 4003
      protocol: TCP
