kind: Deployment
apiVersion: apps/v1
metadata:
  name: freelance-elast
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freelance-elast
  strategy:
    type: Recreate
  minReadySeconds: 10
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
  template:
    metadata:
      labels:
        app: freelance-elast
    spec:
      initContainers:
        - name: busybox
          image: busybox
          imagePullPolicy: Always
          command:
            ['sh', '-c', 'chown -R 1000:1000 /usr/share/elasticsearch/data']
          volumeMounts:
            - name: elasticsearch-local-storage
              mountPath: /usr/share/elasticsearch/data
      containers:
        - name: freelance-elast
          image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: '1500m'
              memory: '5Gi'
            requests:
              cpu: 250m
              memory: 5Gi
          env:
            - name: discovery.type
              value: single-node
            - name: ES_JAVA_OPTS
              value: '-Xmx1g -Xms1g'
            - name: bootstrap.memory_lock
              value: 'true'
            - name: xpack.security.enabled
              value: 'true'
            - name: xpack.security.http.ssl.enabled
              value: 'false'
            - name: xpack.security.transport.ssl.enabled
              value: 'false'
            - name: xpack.security.authc.api_key.enabled
              value: 'true'
            - name: xpack.monitoring.collection.enabled
              value: 'true'
            - name: xpack.security.enrollment.enabled
              value: 'true'
            - name: xpack.security.authc.token.enabled
              value: 'true'
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: freelance-backend-secret
                  key: freelance-elasticsearch-password
          ports:
            - name: freelance-elast
              containerPort: 9200
          volumeMounts:
            - name: elasticsearch-local-storage
              mountPath: /usr/share/elasticsearch/data
              subPath: data
      volumes:
        - name: elasticsearch-local-storage
          persistentVolumeClaim:
            claimName: elasticsearch-pvc
